// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMPYRskfCFjMOjBoa_hG2DT9Kq6J9XzQo',
    appId: '1:263048757383:web:945e47c7ee31b66e8bf822',
    messagingSenderId: '263048757383',
    projectId: 'shopease-39d22',
    authDomain: 'shopease-39d22.firebaseapp.com',
    storageBucket: 'shopease-39d22.firebasestorage.app',
    measurementId: 'G-NW7Y49NY6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloYrZBRdMiKwb8GDkwAK8QUydkdc_s18',
    appId: '1:263048757383:android:4611c60ad93c49808bf822',
    messagingSenderId: '263048757383',
    projectId: 'shopease-39d22',
    storageBucket: 'shopease-39d22.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZGWcrfgOToR4qrRQlZHLTOMxS3nG3Cjo',
    appId: '1:263048757383:ios:5511836c460bf71c8bf822',
    messagingSenderId: '263048757383',
    projectId: 'shopease-39d22',
    storageBucket: 'shopease-39d22.firebasestorage.app',
    androidClientId: '263048757383-llrq319a3fhilgdg5bn0lt0baojov9h0.apps.googleusercontent.com',
    iosClientId: '263048757383-2i4f0f8bel1h89lhg71c33743ra4n8gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
